### ISSUE TITLE
Error in LocalNotifications.schedule: TypeError: builder.setChannelId is not a function (Android)

### ISSUE THREAD

**Issue by flaion** [EddyVerbruggen/nativescript-local-notifications#79]
```
LocalNotifications.schedule([{
      id: 1,
      title: 'The title',
      body: 'Recurs every minute until cancelled',
      ticker: 'The ticker',
      badge: 1,
      at: new Date(new Date().getTime()) // 10 seconds from now
    }]).then(
        function() {
          console.log("Notification scheduled");
        },
        function(error) {
          console.log("scheduling error: " + error);
        }
    )

**Comment by muthukumaroptisol** [comment]
Me also face the same issue. 

Any solution ?

**Comment by nmandyam** [comment]
Was this resolved in some manner? Happens on a Pixel XL with Android 8.0.0. I use TNS 4.0.2.

**Comment by EddyVerbruggen** [comment]
Please reopen with a stacktrace captured from `adb logcat` in case this still happens with plugin version 3.0.0.
